spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 952584713-gacaoe376rltnij4n2qq9cotr4nkhe8o.apps.googleusercontent.com
            client-secret: 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

jwt:
  issuer: mk.kang@dongbuled-s.com
  secret_key: study-springboot
